server:
  port: 2022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 172.26.40.160
    port: 5672
    username: rabbitmq
    password: Chinadci.07
  #设置发送邮箱
  mail:
    #配置 SMTP 服务器地址
    host: smtp.qq.com
    #SMTP 服务器的端口
    port: 587
    #配置邮箱用户名
    username: xxxxxxx@qq.com
    #配置密码，注意，不是真正的密码，而是刚刚申请到的授权码
    password: ikptlejkpcyybbeh
    #默认的邮件编码
    default-encoding: UTF-8
    properties:
      mail:
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
        smtp:
          #配饰 SSL 加密工厂
          socketFactoryClass: javax.net.ssl.SSLSocketFactory