server:
  port: 2021

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.26.40.160:5432/postgres
    username: postgres
    password: Chinadci.07
  redis:
    host: 172.26.40.160
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 6000
  #文件上传大小设置,springboot默认文件大小的限制是1MB,值可以使用后缀“MB”或“KB”.如果是想要不限制文件上传的大小，那么就把两个值都设置为-1
  servlet:
    multipart:
      #单个数据的大小
      max-file-size: 1024MB
      #总数据的大小
      max-request-size: 1024MB
  mvc:
    servlet:
      path: /tplprint
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  gson:
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: printTpl

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
#  http://localhost:2021/tplprint/swagger-ui/index.html
  try-host: http://localhost:${server.port}

mybatis:
  type-aliases-package: com.example.base.pojo
  mapper-locations: classpath*:mapper/postgres/*.xml

#文件存储路径
filepath: ${user.dir}\file

#分页设置
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# rsa配置
rsa:
  key:
    privateKeyFile: D:\\test\\auth\\priKey.key
    publicKeyFile: D:\\test\\auth\\pubKey.key
    secret: (EMOK:)_$^11244^%$_(IS:)_@@++--(COOL:)_++++_.sds_(GUY:)



